name: Docker CI/CD Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Frontend Docker image
    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./bitcoin_explorer_ui
        file: ./bitcoin_explorer_ui/Dockerfile
        push: true
        tags: jing0630/bitcoin-explorer-frontend:latest

    # Build and push Backend Docker image
    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./bitcoin_data_ingestion
        file: ./bitcoin_data_ingestion/Dockerfile
        push: true
        tags: jing0630/bitcoin-explorer-backend:latest

